# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "" # Use the sha or tag you want to point at
      hooks:
          - id: prettier
