name: Release

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
    push:
        branches:
            - master

jobs:
    release:
        name: Release
        runs-on: ubuntu-18.04
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js (.nvmrc)
              uses: actions/setup-node@v2
              with:
                  node-version: "15.2.0"
            - uses: pnpm/action-setup@v1.2.1
              with:
                  version: 5.13.1
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm run build
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
